### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by MoonUniverse** [AlDCheng/BundleFusionUbuntuKinectV2#1]
Thank you for your work!
Will you provide an introduction on how to use this project in the future?

**Comment by AlDCheng** [comment]
Hey, sorry about the state of the repo. Just using it to store code for now; so I haven't tested it in a clean environment.

In any case, this is only a slight modification of this implementation of bundlefusion (https://github.com/FangGet/BundleFusion_Ubuntu_Pangolin). (In hindsight, this should really be a fork of that repository so I may recreate this repo as a fork of that)

Dependencies are the same as what's listed there, as well as Libfreenect2 (https://github.com/OpenKinect/libfreenect2). So a full list is:

- Eigen 3.1.0
- NVIDIA CUDA 9.0/10.+
- OpenCV (I use OpenCV 4.1.0)
- LibFreenect2
- Pangolin

Building is done the same way as above, so:

```
mkdir build && cd build
cmake -DVISUALIZATION=ON ..
make -j8
```

where -DVISUALIZATION=OFF/ON toggles the pangolin visualization.

Hopefully this works for you. I'll find time later to test it on a clean environment to double check this.

**Comment by MoonUniverse** [comment]
Thanks for the reply!

**Comment by AlDCheng** [comment]
Just a small note: I've decided to move this into a fork of the stated original repository, as I've decided that makes more sense. Feel free to put any issues there (https://github.com/AlDCheng/BundleFusion_Ubuntu_Pangolin)
